//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baixes_Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adreces
    {
        public int AdrecesId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<double> n { get; set; }
        public Nullable<double> ngs { get; set; }
        public Nullable<int> ns { get; set; }
        public string Seccio { get; set; }
        public string NomGrup { get; set; }
        public string Direccion { get; set; }
        public string tv { get; set; }
        public string c { get; set; }
        public Nullable<double> num { get; set; }
        public string anum { get; set; }
        public string ps { get; set; }
        public string pt { get; set; }
        public Nullable<double> cp { get; set; }
        public string poblacio { get; set; }
        public string provincia { get; set; }
        public string observacions { get; set; }
        public string Hyperlink { get; set; }
        public string districte { get; set; }
        public string Comarca { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual LatLon LatLon { get; set; }
    }
}
