//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baixes_Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Groups()
        {
            this.Contactes = new HashSet<Contactes>();
            this.Servidors = new HashSet<Servidors>();
            this.Transports = new HashSet<Transports>();
            this.Horari = new HashSet<Horari>();
        }
    
        public int GrupsId { get; set; }
        public Nullable<int> SectionNumber { get; set; }
        public string NomGrup { get; set; }
        public Nullable<bool> Opened { get; set; }
    
        public virtual Acces Acces { get; set; }
        public virtual Adreces Adreces { get; set; }
        public virtual Festius Festius { get; set; }
        public virtual Sections Sections { get; set; }
        public virtual Locals Locals { get; set; }
        public virtual Mails Mails { get; set; }
        public virtual Obertes Obertes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contactes> Contactes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servidors> Servidors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transports> Transports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horari> Horari { get; set; }
    }
}
