//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baixes_Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mails
    {
        public int MailsId { get; set; }
        public int GroupsId { get; set; }
        public Nullable<double> n { get; set; }
        public Nullable<double> ngs { get; set; }
        public string ns { get; set; }
        public string Seccio { get; set; }
        public string NomGrup { get; set; }
        public string EMail { get; set; }
    
        public virtual Groups Groups { get; set; }
    }
}
