//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baixes_Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obertes
    {
        public int ObertesId { get; set; }
        public string Oberta { get; set; }
        public string Observacions { get; set; }
    
        public virtual Groups Groups { get; set; }
    }
}
