//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baixes_Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transports
    {
        public int TransportsId { get; set; }
        public int GroupsId { get; set; }
        public double n { get; set; }
        public Nullable<double> ngs { get; set; }
        public Nullable<int> ns { get; set; }
        public string Seccio { get; set; }
        public string NomGrup { get; set; }
        public string Tipus { get; set; }
        public string Linia { get; set; }
        public string Estacio { get; set; }
        public string Link { get; set; }
    
        public virtual Groups Groups { get; set; }
    }
}
