//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sql_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exports
    {
        public int ExportsId { get; set; }
        public Nullable<System.DateTime> InicioProceso { get; set; }
        public string IssueKey { get; set; }
        public string StatusKey { get; set; }
        public Nullable<int> EmpleadoId { get; set; }
        public string Nombre { get; set; }
        public string Nif { get; set; }
        public string ExportIdentificator { get; set; }
        public string ExportName { get; set; }
        public string Mail { get; set; }
        public string StatusExport { get; set; }
        public string ErrorExport { get; set; }
        public Nullable<System.DateTime> UpdateProcess { get; set; }
        public string Folder { get; set; }
        public string StatusDrive { get; set; }
        public string MailResponsible { get; set; }
        public Nullable<decimal> SizeInBytes { get; set; }
        public string StatusTransfer { get; set; }
        public string StatusProcess { get; set; }
        public string StatusAd { get; set; }
        public string WindowsId { get; set; }
        public string StatusAlias { get; set; }
        public string StatusGoogleUser { get; set; }
        public string Password { get; set; }
    }
}
