//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sql_Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class LogPBajasA
    {
        public int LogBajasId { get; set; }
        public Nullable<System.DateTime> StartProcess { get; set; }
        public string Ticket { get; set; }
        public string StatusTicket { get; set; }
        public string Name { get; set; }
        public string WindowsId { get; set; }
        public string Mail { get; set; }
        public string Nif { get; set; }
        public string ResponsableTicket { get; set; }
        public string ResponsableAd { get; set; }
        public string StatusProcess { get; set; }
        public Nullable<System.DateTime> ChangeStatusP { get; set; }
        public Nullable<bool> BackupMail { get; set; }
        public Nullable<bool> BackupDrive { get; set; }
        public Nullable<bool> Transfer { get; set; }
        public Nullable<bool> DeleteAd { get; set; }
        public Nullable<int> EmployeeNumber { get; set; }
        public Nullable<bool> CreateAlias { get; set; }
    }
}
