//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sql_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int UsuariosId { get; set; }
        public string windowsid { get; set; }
        public string nombre { get; set; }
        public string date { get; set; }
        public Nullable<int> level { get; set; }
    }
}
